language: go

matrix:
  include:
    - go: 1.10.x
    - go: tip
  allow_failures:
    - go: tip

sudo: required

services:
  - docker

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y gcc libkrb5-dev

install: true

script:
  - go vet ./...
  - go fmt ./...
  - go test -v -race ./...
  - cd test/
  - ./run-heimdal.sh
